#!/bin/bash
#
#       /etc/rc.d/init.d/gogoc
#
# Starts the gogoc service
#
# chkconfig: 345 95 5
# description: Runs the IPv6 tunnel from go6.net
# processname: gogoc

# Source function library.
. /etc/init.d/functions

test -x /usr/local/gogoc/bin/gogoc || exit 0

RETVAL=0

#
#       See how we were called.
#

prog="gogoc"

start() {
        # Check if gogoc is already running
        if [ ! -f /var/lock/subsys/gogoc ]; then
            echo -n $"Starting $prog: "
            daemon /usr/local/gogoc/bin/gogoc -f /usr/local/gogoc/etc/gogoc.conf
            RETVAL=$?
            [ $RETVAL -eq 0 ] && touch /var/lock/subsys/gogoc
            echo
        fi
        return $RETVAL
}

stop() {
	pidof radvd >/dev/null && (
		echo -n $"Stopping radvd: "
		killproc /usr/local/gogoc/sbin/gogoc
	)
        echo -n $"Stopping $prog: "
        killproc /usr/local/gogoc/bin/gogoc
        RETVAL=$?
        rm -f /var/lock/subsys/gogoc
        echo
        return $RETVAL
}


restart() {
        stop
        start
}

reload() {
        restart
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
reload|restart)
        restart
        ;;
condrestart)
        if [ -f /var/lock/subsys/gogoc ]; then
            restart
        fi
        ;;
*)
        echo $"Usage: $0 {start|stop|restart|condrestart}"
        exit 1
esac

exit $?
exit $RETVAL
